
_ENV=namespace("ENUM")

BATTLE_RESULT_STATUS={
    WIN=1,
    LOSE=2,
    WAIT=3,
    UNKOWN=4
}


SKILL_STATUS={
    AVALIBLE=1,
    BALL_NOT_ENOUGH=2,
    MP_NOT_ENOUGH=3,
    NOT_AVALIBLE=4,
    BAN=5,
}

BATTLESPRITE_STATUS={
    NORMAL=1,
}
SKILL_DIRECTION={
    JIAN_LEFT=1;
    JIAN_RIGHT=2;
    JIAN_UPPER=3;
    JIAN_LOWWER=4;
    DAO_LEFT_RIGHT=5;
    DAO_UP_DOWN=6;
    ALL=7;
}






NET_BATTLE={
    START="LUA_START",
    END="LUA_END",
    MY_TURN="LUA_MY_TURN",
    YOUR_TURN="LUA_YOUR_TURN",
    ATTACK="LUA_ATTACK",
    MOVE="LUA_MOVE",
    USEITEM="LUA_USEITEM",
    REST="LUA_REST",
    DATA="LUA_DATA",
    ROLE_INFO="LUA_ROLE_INFO",
    SERVER_OK="LUA_SERVER_OK",
    CLIENT_OK="LUA_CLIENT_OK",
    ON_RESULT="LUA_ON_RESULT",
    UP_TIME="LUA_UP_TIME",
    REMOVE_SPRITE="LUA_REMOVE_SPRITE",
}